#!/bin/sh

set -x

. ${srcdir}/functions

echo "Testing normal archival creation/extraction with default compression"
rm -rf bin2.xar bin2
ln -s /bin bin2
${XAR} -cf bin2.xar bin2
rm -f bin2
if [ $? -ne 0 ]; then
	echo "Error creating archive"
	exit 1
else
    du -k bin2.xar
fi

${XAR} -xf bin2.xar
if [ $? -ne 0 ]; then
	echo "Error extracting archive"
	exit 1
fi

if [ ! -e bin2/sh ]; then
	echo "Error with extracted contents"
        exit 1
fi

echo "Testing normal archival creation/extraction with gzip compression"
rm -rf bin2.xar bin2
ln -s /bin bin2
${XAR} --compression=gzip -cf bin2.xar bin2
rm -f bin2
if [ $? -ne 0 ]; then
	echo "Error creating archive"
	exit 1
else
    du -k bin2.xar
fi

${XAR} -xf bin2.xar
if [ $? -ne 0 ]; then
	echo "Error extracting archive"
	exit 1
fi

if [ ! -e bin2/sh ]; then
	echo "Error with extracted contents"
        exit 1
fi

echo "Testing normal archival creation/extraction with bzip2 compression"
rm -rf bin2.xar bin2
ln -s /bin bin2
${XAR} --compression=bzip2 -cf bin2.xar bin2
rm -f bin2
if [ $? -ne 0 ]; then
	echo "Error creating archive"
	exit 1
fi

${XAR} -xf bin2.xar
if [ $? -ne 0 ]; then
	echo "Error extracting archive"
	exit 1
else
    du -k bin2.xar
fi

if [ ! -e bin2/sh ]; then
	echo "Error with extracted contents"
        exit 1
fi

echo "Testing normal archival creation/extraction with lzma compression"
rm -rf bin2.xar bin2
ln -s /bin bin2
${XAR} --compression=lzma -cf bin2.xar bin2
rm -f bin2
if [ $? -ne 0 ]; then
	echo "Error creating archive"
	exit 1
else
    du -k bin2.xar
fi

${XAR} -xf bin2.xar
if [ $? -ne 0 ]; then
	echo "Error extracting archive"
	exit 1
fi

if [ ! -e bin2/sh ]; then
	echo "Error with extracted contents"
        exit 1
fi

echo "Testing normal archival creation/extraction with no compression"
rm -rf bin2.xar bin2
ln -s /bin bin2
${XAR} --compression=none -cf bin2.xar bin2
rm -f bin2
if [ $? -ne 0 ]; then
	echo "Error creating archive"
	exit 1
else
    du -k bin2.xar
fi

${XAR} -xf bin2.xar
if [ $? -ne 0 ]; then
	echo "Error extracting archive"
	exit 1
fi

if [ ! -e bin2/sh ]; then
	echo "Error with extracted contents"
        exit 1
fi
rm -rf bin2.xar bin2
ln -s /bin bin2
${XAR} --compression=none -cf bin2.xar bin2
rm -f bin2
if [ $? -ne 0 ]; then
	echo "Error creating archive"
	exit 1
fi

${XAR} -xf bin2.xar
if [ $? -ne 0 ]; then
	echo "Error extracting archive"
	exit 1
fi

if [ ! -e bin2/sh ]; then
	echo "Error with extracted contents"
fi

rm -rf bin2.xar bin2
echo "Success testing compression types"
