#!/bin/bash

. ${srcdir}/functions

echo "Checking hardlinks in a directory"

rm -rf i i1 i.xar
mkdir i i1
touch i/a
ln i/a i/b

create_archive i.xar i

cd i1
extract_archive ../i.xar
check_hardlink "i/a" "i/b"
cd ..
rm -rf i i1 i.xar

echo "Checking hardlinks in ."
mkdir -p i i1
cd i
touch a
ln a b
create_archive ../i.xar .
cd ../i1
extract_archive ../i.xar
check_hardlink "a" "b"
cd ..
rm -rf i i1 i.xar

echo "Checking link extraction (no original)"
rm -rf i i1 i.xar
mkdir i i1
touch i/a
ln i/a i/b
create_archive i.xar i
cd i1
extract_archive ../i.xar
if [ ! -f i/b ]; then
	echo "Error extracting link"
	exit 1;
fi
cd ..
rm -rf i i1 i.xar

echo "Hardlink success"
