.\" xar.1
.\"
.\" Copyright (c) 2005 Rob Braun
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Rob Braun nor the names of its
.\"    contributors may be used to endorse or promote products derived from
.\"    this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd Jan 25, 2005
.Dt XAR 1 "OpenDarwin Project"
.Os
.Sh NAME
.Nm xardiff
.Nd xardiff command; compare xar files and files/directory hierarchies
.Sh SYNOPSIS
.Nm
.Op Fl a
.Op Ar archive1.xar
.Op Ar archive2.xar
.Sh DESCRIPTION
.Nm
is a tool for finding differences between two xar files, or between
a xar file and a directory hierarchy, or between two directory hierarchies.
If one of the comparison arguments is not a xar file,
.Nm
will attempt to create a xar table of contents for the argument.  If
a directory is specified,
.Nm
will recurse down the directory, building a table of contents.
.Nm
will then compare the table of contents of the two arguments, displaying
differences as they are found.  This can be useful for comparing a
backup with the original directory hierarchy to find changes.
Note that a full xar archive is not needed for the comparison, since
the heap section of the xar archive is never referenced.  You can use
the table of contents as generated by a "xar -cnf" command.

.Sh COMMANDS
Exactly one of the following commands must be specified:
.Bl -tag -width -ident
.It Fl a
Ignore any differences in atimes.  atimes are updated frequently,
and can clutter the output.
.El
.Sh AUTHORS
.An Rob Braun Aq bbraun@opendarwin.org
